### ISSUE TITLE
包裝、上傳「座標快速反查地理區域(行政區、保護區、河川流域等)索引演算法」

### ISSUE THREAD

**Issue by cjk-halodule** [TaiBIF/gpm#3]
請將程式碼及設定包裝、上傳至 github.com/TaiBIF/coordinateToAdminArea，若有帳密內容則上傳至同名私有 repo.

**Comment by trashmai** [comment]
已將 db schema (含 data) 與資料處理、API 與 library 程式碼上傳，並將過時的 php mysql 語法改為 PDO 的寫法。
